// VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=humao.rest-client

// List all blog posts
GET http://127.0.0.1:3200

###
// Create a new blog post
POST http://127.0.0.1:3200/
content-type: application/json

{
  "title": "My new blog post",
  "body": "This is my new blog post. It's so cool!"
}

###
// Update an existing blog post - id is a path parameter
PUT http://127.0.0.1:3200/:id
content-type: application/json

{
  "title": "My updated blog post",
  "body": "This is my updated blog post. It's so awesome!",
  "image": "https://www.google.com/images/branding/googlelogo/1x/googlelogo_color_272x92dp.png"
}

###
// Delete an existing blog post - id is a path parameter
DELETE http://127.0.0.1:3200/:id

###
// Get a single blog post - id is a path parameter
GET http://127.0.0.1:3200/:id